package com.prama.phoebe;

public class Map {
	
	// Liste des matrices (map où mène la TP)
	public static short[] matrixArray = {  
			  0,   0,   2,   0, 122, 123, 116, 117, 141, 142, 143, 148, 149, 150, 151, 152,
			153, 154, 207, 132, 208, 208, 208, 125, 132, 208, 208, 208, 205, 140, 132, 125, 
			125,   0, 122, 112, 116, 117, 217, 218, 219, 123, 123, 243, 243,   0, 122, 113, 
			116, 117, 132, 208, 136, 208, 132, 208, 136, 208, 123, 155, 123, 132, 208, 208, 
			123,   0, 122, 220, 221, 116, 117, 138, 132, 133, 134, 208, 132, 135, 208, 208, 
			159, 170, 124, 124, 244, 123,   0, 122, 222, 223, 223, 224, 223, 224, 223, 224, 
			223, 223, 223, 223, 225, 116, 117, 209, 210, 207, 156, 157, 157, 158, 158, 157, 
			209, 210, 207, 125, 237, 165, 166, 167,   0, 206, 111, 116, 117, 181,  18, 123, 
			123, 125, 123, 123,   0, 115, 116, 117, 139, 172, 173, 174, 175, 176, 207, 177, 
			204, 125, 125, 123, 123, 158,   0, 116, 117, 122, 226, 227, 228, 203, 243, 244, 
			243, 243, 243, 125, 230,   0, 122, 114, 116, 117, 123, 123,   0, 116, 117, 144, 
			187, 183, 188, 184, 188, 185, 188, 186, 189, 190, 192, 191,   0, 116, 117, 122, 
			159, 157, 123, 123, 123,   5,   5,   6,   0, 234,   0,   7,   0,   8,   0,   9, 
			 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,   2,  21,  22,  23,   0,  24,
			  0,  25,  26,  40,  35,  39,  31,  34,  31,  40,  42,  35,  35,  36,  34,  30,
			 41,  31,  35,   0,  43,  44,  45,  46,  47,  48,  49,  49,   0,  50,  51,  52,
			 52, 123,   3,   4,   0,  53,   0,  57,  58,  59,   0,  60,  61,  62,  63,  64,
			 64,  65,   0, 123,   0,   0,  68,  69,  70,  71,  72,  73,  74,  75,  76,  79,
			  0,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
			157,  95,  96,  97,  98, 100,  99, 101, 102, 103, 104, 105, 106, 107, 108, 109,
			  0, 110, 229, 231, 232, 233, 193, 207, 194, 195, 197, 198, 118, 121,   0, 123,
			  0, 147, 146, 146,   0,   0,   0,   0,   0,   0,   0,   0, 243,   0,   0, 211,
			157,   0,   0, 123,   0, 212, 213, 214, 215, 216,   0,   0, 123,   0,   0,   0,
			178, 179, 180,   0, 244,   0, 158, 125, 145, 146, 146, 146,   0, 157,   0,   0,
			243,   0, 124, 124,   0, 158, 158,   0,   0, 201, 244,   0, 123, 123, 158,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 119,   0, 126, 127, 128, 129,
			123, 123,   0, 122, 116, 117, 160, 130, 131, 123,   0, 122, 116, 117, 236, 123,
			123,   0, 122, 116, 117, 137, 123, 244, 123, 123,   0, 116, 117, 168, 170, 124, 
			124, 169,   0, 122, 116, 117, 123, 125, 123,   0, 122, 116, 117, 199, 200, 207,
			123, 123, 120,   0,   0,   0,   0,   0,   0,   0, 235, 235, 235, 235, 235, 235,
			235, 235, 235, 235, 235, 235, 235, 235, 235, 235, 235, 124, 171, 196, 238, 117, 
			235, 239, 123, 244, 243, 158, 244, 125, 240, 240, 240, 240, 240, 240, 241, 242, 
			 77,  78, 243,  31, 207, 208,  65,  66,  66,  64,  64,  65,  65,  66,  66,  64,
			 64,  65,  65,  66,  66,  64,  64,  65,  65,  66,  66,  64,  64,  65,  65,  66,
			 66,  64,  64,  65,  65,  66,  66,  64,  64,  65,  65,  66,  66,  66, 166};
	
	public static String[] noms = {
			"Sinnoh",
			"Zone Mystère",
			"Souterrain",
			"Extérieur",
			"Magasin (Féli-Cité)",
			"??? (Arène?, Féli-Cité)",
			"Centre Pokémon - RC (Féli-Cité)",
			"Centre Pokémon - Étage (Féli-Cité)",
			"Pokémontre S.A - RC",
			"Pokémontre S.A - 1er étage",
			"Pokémontre S.A - 2nd étage",
			"Féli-Télé - RC",
			"Féli-Télé - 1er étage",
			"Féli-Télé - 2nd étage",
			"Féli-Télé - 3ème étage",
			"Féli-Télé - 4ème étage",
			"Féli-Télé - 5ème étage",
			"Féli-Télé - 6ème étage",
			"Féli-Télé - Ascenseur",
			"Maison 1 - RC (Féli-Cité)",
			"Maison 1 - 1er étage (Féli-Cité)",
			"Maison 1 - 2nd étage (Féli-Cité) [INUTILISE]",
			"Maison 1 - 3ème étage (Féli-Cité) [INUTILISE]",
			"Impossible à charger (Féli-Cité)",
			"Résidence de Féli-Cité - RC",
			"Résidence de Féli-Cité - 1er étage",
			"Résidence de Féli-Cité - 2nd étage [INUTILISE]",
			"Résidence de Féli-Cité - 3ème étage [INUTILISE]",
			"GTS",
			"École des Dresseurs",
			"Bâtiment près de la GTS - RC",
			"Bâtiment près de la GTS - Étage",
			"Impossible à charger (Féli-Cité)",
			"Joliberges (Extérieur)",
			"Magasin (Joliberges)",
			"Arène (Joliberges)",
			"Centre Pokémon - RC (Joliberges)",
			"Centre Pokémon - 1er étage (Joliberges)",
			"Bibliothèque - RC (Joliberges)",
			"Bibliothèque - 1er étage (Joliberges)",
			"Bibliothèque - 2nd étage (Joliberges)",
			"Maison 1 (Joliberges)",
			"Maison de l'Effaceur de Capacités (Joliberges)",
			"Maison bloquée [Darkrai] (Joliberges)",
			"Maison du Marin (Joliberges)",
			"Charbourg (Extérieur)",
			"Magasin (Charbourg)",
			"Arène (Charbourg)",
			"Centre Pokémon - RC (Charbourg)",
			"Centre Pokémon - Étage (Charbourg)",
			"1er bâtiment - RC (Charbourg)",
			"1er bâtiment - 1er étage (Charbourg)",
			"1er bâtiment - 2nd étage (Charbourg) [INUTILISE]",
			"1er bâtiment - 3ème étage (Charbourg) [INUTILISE]",
			"2nd bâtiment - RC (Charbourg)",
			"2nd bâtiment - 1er étage (Charbourg)",
			"2nd bâtiment - 2nd étage (Charbourg) [INUTILISE]",
			"2nd bâtiment - 3ème étage (Charbourg) [INUTILISE]",
			"Maison à gauche du Musée Minier",
			"Musée Minier",
			"Maison à gauche de l'Arène (Charbourg)",
			"Immeuble le plus à l'Est - RC (Charbourg)",
			"Immeuble le plus à l'Est - 1er étage (Charbourg)",
			"Immeuble le plus à l'Est - 2nd étage (Charbourg) [INUTILISE]",
			"Maison près de la Mine",
			"Vestigion (Extérieur)",
			"Magasin (Vestigion)",
			"Arène - Entrée (Vestigion)",
			"Arène - Arène (Vestigion)",
			"Centre Pokémon - RC (Vestigion)",
			"Centre Pokémon - Étage (Vestigion)",
			"Boutique de Vélos",
			"QG Galaxie - RC (Vestigion)",
			"QG Galaxie - 1er étage (Vestigion)",
			"QG Galaxie - 2nd étage (Vestigion)",
			"QG Galaxie - 3ème étage (Vestigion)",
			"Résidence de Vestigion - RC",
			"Résidence de Vestigion - 1er étage",
			"Résidence de Vestigion - 2nd étage",
			"Résidence de Vestigion - 3ème étage",
			"Passerelle (Vestigion - Route 206)",
			"Herboristerie",
			"Maison de Chen",
			"Maison au Sud de la Statue (Vestigion)",
			"Maison de l'Homme du Souterrain",
			"Impossible à charger (Vestigion)",
			"Unionpolis (Extérieur)",
			"Magasin (Unionpolis)",
			"Arène - Entrée (Unionpolis)",
			"Arène - 1 (Unionpolis)",
			"Arène - 2 (Unionpolis)",
			"Arène - 3 (Unionpolis)",
			"Arène - 4 (Unionpolis)",
			"Arène - 5 (Unionpolis)",
			"Arène - 6 (Unionpolis)",
			"Arène - 7 (Unionpolis)",
			"Arène - 8 (Unionpolis)",
			"Arène - 9 (Unionpolis)",
			"Arène - 10 (Unionpolis)",
			"Arène - 11 (Unionpolis)",
			"Arène - Salle de Kiméra (Unionpolis)",
			"Centre Pokémon - RC (Unionpolis)",
			"Centre Pokémon - 1er étage (Unionpolis)",
			"Résidence à droite du Fan Club - RC",
			"Résidence à drotie du Fan Club - Étage",
			"Résidence à droite du Fan Club - Ascenseur",
			"Fan Club Pokémon",
			"Passerelle Ouest (Unionpolis - Parc)",
			"Passerelle Est (Unionpolis - Parc)",
			"Passerelle (Unionpolis - Route 208)",
			"Passerelle (Unionpolis - Route 209)",
			"Passerelle (Unionpolis - Route 212)",
			"Résidence à gauche de l'Arène - RC (Unionpolis)",
			"Résidence à gauche de l'Arène - Étage (Unionpolis)",
			"Résidence à gauche de l'Arène - Ascenseur (Unionpolis)",
			"Maison d'Amelle",
			"Poffinerie",
			"Entrée de la Salle Concours",
			"Salle Concours",
			"Podium de la Salle Concours",
			"Verchamps (Extérieur)",
			"Magasin (Verchamps)",
			"Arène (Verchamps)",
			"Centre Pokémon - RC (Verchamps)",
			"Centre Pokémon - Étage (Verchamps)",
			"Entrée du Grand Marais",
			"Observatoire du Grand Marais",
			"Maison au Sud - Ouest (Verchamps)",
			"Maison en haut du Magasin (Verchamps)",
			"Maison en haut à droite du Magasin (Verchamps)",
			"Maison à droite de l'Arène (Verchamps)",
			"Maison au Nord - Est (Verchamps)",
			"Voilaroc (Extérieur)",
			"Centre Pokémon - Sous-Sol (Voilaroc)", // NB : apparemment, ça serait plutôt 480.
			"Centre Pokémon - RC (Voilaroc)",
			"Centre Pokémon - Étage (Voilaroc)",
			"Casino",
			"Centre Commercial - RC",
			"Centre Commercial - 1er étage",
			"Centre Commercial - 2nd étage",
			"Centre Commercial - 3ème étage",
			"Centre Commercial - 4ème étage",
			"Centre Commercial - Ascenseur",
			"Entrepôt Galaxie",
			"Bâtiment des Prix du Casino",
			"Maison du Clown Triste (Voilaroc)",
			"1ère Maison à droite du Centre Commercial",
			"2ème Maison à droite du Centre Commercial",
			"Maison de la Masseuse",
			"Passerelle (Voilaroc - Route 215)",
			"Rivamar (Extérieur)",
			"Centre Pokémon - RC (Rivamar)",
			"Centre Pokémon - Étage (Rivamar)",
			"Magasin (Rivamar)",
			"Arène - 1ère salle (Rivamar)",
			"Arène - 2nde salle (Rivamar)",
			"Arène - Salle de Tanguy",
			"Marché (Rivamar)",
			"Maison de Claudie (Rivamar)",
			"Maison du Souterrain (Rivamar)",
			"Maison d'Hélio (Rivamar)",
			"Maison retirée du jeu (Rivamar)",
			"Maison retirée du jeu (Rivamar)",
			"Maison du développeur Pokémontre (Rivamar)",
			"Phare Panorama",
			"Frimapic (Extérieur)",
			"Magasin (Frimapic)",
			"Arène (Frimapic)",
			"Centre Pokémon - RC (Frimapic)",
			"Centre Pokémon - Étage (Frimapic)",
			"Maison Ouest (Frimapic)",
			"Maison Est (Frimapic)",
			"Ligue Pokémon (Extérieur)",
			"Centre Pokémon - RC (Ligue Pokémon)",
			"Centre Pokémon - Étage (Ligue Pokémon)",
			"Hall de la Ligue",
			"Couloir vers Aaron",
			"Salle d'Aaron",
			"Couloir vers Terry",
			"Salle de Terry",
			"Couloir vers Adrien",
			"Salle d'Adrien",
			"Couloir vers Lucio",
			"Salle de Lucio",
			"Chemine vers Cynthia",
			"Salle de Cynthia",
			"Chemin vers le Panthéon",
			"Panthéon",
			"Aire de Combat (Extérieur)",
			"Centre Pokémon - RC (Aire de Combat)",
			"Centre Pokémon - Étage (Aire de Combat)",
			"Magasin (Aire de Combat)",
			"Passerelle (Aire de Combat - Parc des Combats)",
			"Maison Est (Aire de COmbat)",
			"Maison Ouest (Aire de Combat)",
			"Maison vide, sortie impossible (Aire de Survie?)",
			"Entrée de la mine, impossible à charger",
			"Entrée de la Mine de Charbourg",
			"Mine de Charbourg",
			"Éoliennes (Extérieur)",
			"Éoliennes (Intérieur)",
			"Forêt de Vestigion (Extérieur)",
			"Forêt de Vestigion (Intérieur)",
			"Forge Fuego (Extérieur)",
			"Forge Fuego (Intérieur)",
			"??? (Zone Mystère Extérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"??? (Mont Couronné intérieur)",
			"Colonnes Lances (avec évènements)",
			"Colonnes Lances (sans évènements)",
			"??? (Zone Mystère extérieur)",
			"Grand Marais - Zone bêta",
			"??? (Zone Mystère extérieur)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Ruines Bonville)",
			"??? (Zone Mystère extérieur)",
			"Route Victoire 1",
			"Route Victoire 2",
			"Route Victoire 3",
			"Route Victoire 4",
			"Route Victoire 5",
			"Route Victoire 6",
			"Parc des Amis",
			"???",
			"Zone mystère extérieure",
			"Square Paisible",
			"Chemin Rocheux",
			"Zone Mystère - Pré Floraville", // ?
			"Pré Floraville",
			"Maison (Pré Floraville)",
			"Entrée Charbourg",
			"Entrée Charbourg",
			"Île Pleine Lune (Extérieur)",
			"Île Pleine Lune (Intérieur)",
			"Mont Abrupt (Extérieur)",
			"Mont Abrupt 1",
			"Mont Abrupt 2",
			"Mont Abrupt (Heatran)",
			"Zone Mystère Extérieur",
			"Source Adieu",
			"Entrée de la Grotte Retour",
			"Grotte Retour - 1",
			"Grotte Retour (Giratina)",
			"Grotte Retour - 2",
			"Grotte Retour - 3",
			"Grotte Retourn - 4",
			"Paradis Fleuri (Extérieur)",
			"Maison vide (Zone Mystère ?)",
			"Zone Mystère Extérieur",
			"Zone Mystère Extérieur",
			"Temple Frimapic - 1",
			"Temple Frimapic - 2",
			"Temple Frimapic - 3",
			"Temple Frimapic - 4",
			"Temple Frimapic - 5",
			"Temple Frimapic (Regigigas)",
			"Grotte Revêche - 1",
			"Grotte Revêche - 2",
			"Grotte Ruinemaniac",
			"Jardin Trophée",
			"Île de Fer (Extérieur)",
			"Île de Fer - 1",
			"Île de Fer - 2",
			"Île de Fer - 3",
			"Île de Fer - 4",
			"Île de Fer - 5",
			"Île de Fer - 6",
			"Vieux Château",
			"Vieux Château",
			"Vieux Château",
			"Vieux Château",
			"Vieux Château",
			"Vieux Château",
			"Vieux Château",
			"Vieux Château",
			"Vieux Château",
			"Passerelle Verticale (?)",
			"QG Galaxie - RDC (Voilaroc)",
			"QG Galaxie (Voilaroc)",
			"QG Galaxie (Voilaroc)",
			"QG Galaxie (Voilaroc)",
			"QG Galaxie (Voilaroc)",
			"QG Galaxie (Voilaroc)",
			"Lac Vérité",
			"Lac Vérité",
			"Lac Vérité - Caverne",
			"Lac Courage",
			"Lac Courage",
			"Lac Courage - Caverne",
			"Lac Savoir",
			"Lac Savoir",
			"Lac Savoir - Caverne",
			"Île Nouvellelune (Extérieur)",
			"Île Nouvellelune (Intérieur)",
			"Parc des Combats",
			"Parc des Combats",
			"Salle inconnue 1",
			"Salle inconnue 2",
			"Hall de la Tour de Combat",
			"Ascenseur de la Tour de Combat",
			"Tour de Combat",
			"Tour de Combat",
			"Tour de Combat",
			"Tour de Combat",
			"Salle de Combat Multi",
			"Salle de Combat Multi (Tapis plus long)",
			"Rive Lac Vérité (Extérieur)",
			"Rive Lac Vérité (Maison)",
			"Rive Lac Courage",
			"Grand Lac",
			"Grand Lac",
			"Rive Lac Savoir (Extérieur)",
			"Chemin Source (Extérieur)",
			"Route 201 (Extérieur)",
			"Route 202 (Extérieur)",
			"Route 204 (Extérieur)",
			"Route 204 (Extérieur)",
			"Route 205 (Extérieur)",
			"Route 205 (Extérieur)",
			"Route 205 (Extérieur)",
			"Route 206 (Extérieur)",
			"Passerelle",
			"Passerelle verticale",
			"Route 207 (Extérieur)",
			"Route 208 (Extérieur)",
			"Route 208 - Maison",
			"Route 209 (Extérieur)",
			"Route 209 - Tour",
			"Route 209 - Tour",
			"Route 209 - Tour",
			"Route 209 - Tour",
			"Route 209 - Tour",
			"Route 210 (Extérieur)",
			"Route 210 (Extérieur)",
			"Route 210 - Maison",
			"Route 211 (Extérieur)",
			"Route 211 (Extérieur)",
			"Route 211 (Extérieur)",
			"Route 212 (Extérieur)",
			"Hall du Manoir Pokémon",
			"Chambres des \"Femmes de Ménage\"",
			"Salle de \"Mr. Décorum\"",
			"Extérieur",
			"???",
			"Extérieur",
			"???",
			"Abri Petitpas (Route 213)",
			"???",
			"???",
			"???",
			"???",
			"Extérieur",
			"???",
			"Extérieur",
			"Extérieur",
			"???",
			"Extérieur",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"Extérieur",
			"Extérieur",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"???",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Salle d'échange de données ?",
			"Extérieur",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Extérieur",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Salle d'échanges sans fil",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"Extérieur",
			"SS Centre Pokémon Féli-Cité",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Salle Originelle (avec events)",
			"Salle Originelle (sans events)",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Grotte Retour",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"???",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Fausse \"Grotte Retour\" (portes bloquées)",
			"Salle Concours (Gradins et scène)"
	};
	
	private short mapID; // L'ID de la map instanciée
	
	public Map(short mapID) {
		this.mapID = mapID;
	}
	
	// *** GETTERS ***
	public short getMapID() {
		return this.mapID;
	}
	
	public short getMatrix() {
		return Map.matrixArray[this.mapID];
	}
	
	public String getNom() {
		return Map.noms[mapID];
	}
}
